const CARD_DATA_OBJECT =
  {
    deckLimit: 20,
    cards: [
      { _id: 1, name: 'amargasaurus', imgUrl: '/img/amargasaurus.svg', type: 'land', power: 5, cost: 8, special: '', description: '' , doubled: false  },
      { _id: 2, name: 'ampelosaurus', imgUrl: '/img/ampelosaurus.svg', type: 'land', power: 7, cost: 15, special: '', description: '' , doubled: false  },
      { _id: 3, name: 'ankylosaurus', imgUrl: '/img/ankylosaurus.svg', type: 'land', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 4, name: 'apatosaurus', imgUrl: '/img/apatosaurus.svg', type: 'land', power: 1, cost: 10, special: 'meteor', description: 'Meteor: Reduce the power to 1 in the row that it\'s played and your opponents row' , doubled: false  },
      { _id: 5, name: 'azendohsaurus', imgUrl: '/img/azendohsaurus.svg', type: 'land', power: 2, cost: 3, special: '', description: '' , doubled: false  },
      { _id: 6, name: 'bactrosaurus', imgUrl: '/img/bactrosaurus.svg', type: 'land', power: 4, cost: 6, special: '', description: '' , doubled: false  },
      { _id: 7, name: 'basilosaurus', imgUrl: '/img/basilosaurus.svg', type: 'water', power: 9, cost: 25, special: '', description: '' , doubled: false  },
      { _id: 8, name: 'bat', imgUrl: '/img/bat.svg', type: 'air', power: 1, cost: 25, special: 'resurrector', description: 'Resurrector: Has the ability to summon two cards from your discard pile to your hand' , doubled: false  },
      { _id: 9, name: 'beipiaosaurus', imgUrl: '/img/beipiaosaurus.svg', type: 'air', power: 3, cost: 4, special: '', description: '' , doubled: false  },
      { _id: 10, name: 'bird', imgUrl: '/img/bird.svg', type: 'air', power: 1, cost: 7, special: 'paragon', description: 'Paragon: Inspires a 2x morale boost to this row\'s strength' , doubled: false  },
      { _id: 11, name: 'caudipteryx', imgUrl: '/img/caudipteryx.svg', type: 'land', power: 4, cost: 6, special: '', description: '' , doubled: false  },
      { _id: 12, name: 'clam', imgUrl: '/img/clam.svg', type: 'water', power: 1, cost: 10, special: 'meteor', description: 'Resurrector: Has the ability to summon two cards from your discard pile to your hand' , doubled: false  },
      { _id: 13, name: 'coelophysis', imgUrl: '/img/coelophysis.svg', type: 'land', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 14, name: 'dilophosaurus', imgUrl: '/img/dilophosaurus.svg', type: 'land', power: 1, cost: 2, special: '', description: '' , doubled: false  },
      { _id: 15, name: 'elasmosaurus', imgUrl: '/img/elasmosaurus.svg', type: 'water', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 16, name: 'fish', imgUrl: '/img/fish.svg', type: 'water', power: 1, cost: 7, special: 'paragon', description: 'Paragon: Inspires a 2x morale boost to this row\'s strength' , doubled: false  },
      { _id: 17, name: 'hummingbird', imgUrl: '/img/hummingbird.svg', type: 'air', power: 1, cost: 10, special: 'meteor', description: 'Meteor: Reduce the power to 1 in the row that it\'s played and your opponents row' , doubled: false  },
      { _id: 18, name: 'ichthyosaurus', imgUrl: '/img/ichthyosaurus.svg', type: 'water', power: 4, cost: 6, special: '', description: '' , doubled: false  },
      { _id: 19, name: 'iguanodon', imgUrl: '/img/iguanodon.svg', type: 'land', power: 1, cost: 3, special: '', description: '' , doubled: false  },
      { _id: 20, name: 'jellyfish', imgUrl: '/img/jellyfish.svg', type: 'water', power: 8, cost: 20, special: '', description: '' , doubled: false  },
      { _id: 21, name: 'owl', imgUrl: '/img/owl.svg', type: 'air', power: 5, cost: 8, special: '', description: '' , doubled: false  },
      { _id: 22, name: 'parasaurolophus', imgUrl: '/img/parasaurolophus.svg', type: 'land', power: 3, cost: 4, special: '', description: '' , doubled: false  },
      { _id: 23, name: 'pelicanimimus', imgUrl: '/img/pelicanimimus.svg', type: 'land', power: 1, cost: 25, special: 'resurrector', description: 'Resurrector: Has the ability to summon two cards from your discard pile to your hand' , doubled: false  },
      { _id: 24, name: 'plateosaurus', imgUrl: '/img/plateosaurus.svg', type: 'land', power: 7, cost: 15, special: '', description: '' , doubled: false  },
      { _id: 25, name: 'protoceratops', imgUrl: '/img/protoceratops.svg', type: 'land', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 26, name: 'pterodactyl', imgUrl: '/img/pterodactyl.svg', type: 'air', power: 8, cost: 20, special: '', description: '' , doubled: false  },
      { _id: 27, name: 'rhamphorhynchus', imgUrl: '/img/rhamphorhynchus.svg', type: 'air', power: 7, cost: 15, special: '', description: '' , doubled: false  },
      { _id: 28, name: 'sauropelta', imgUrl: '/img/sauropelta.svg', type: 'land', power: 1, cost: 7, special: 'paragon', description: 'Paragon: Inspires a 2x morale boost to this row\'s strength' , doubled: false  },
      { _id: 29, name: 'scelidosaurus', imgUrl: '/img/scelidosaurus.svg', type: 'land', power: 4, cost: 6, special: '', description: '' , doubled: false  },
      { _id: 30, name: 'scutellosaurus', imgUrl: '/img/scutellosaurus.svg', type: 'land', power: 5, cost: 8, special: '', description: '' , doubled: false  },
      { _id: 31, name: 'spinosaurus', imgUrl: '/img/spinosaurus.svg', type: 'land', power: 10, cost: 30, special: '', description: '' , doubled: false  },
      { _id: 32, name: 'starfish', imgUrl: '/img/starfish.svg', type: 'water', power: 1, cost: 25, special: 'resurrector', description: 'Resurrector: Has the ability to summon two cards from your discard pile to your hand' , doubled: false  },
      { _id: 33, name: 'stegosaurus', imgUrl: '/img/stegosaurus.svg', type: 'land', power: 8, cost: 20, special: '', description: '' , doubled: false  },
      { _id: 34, name: 'styracosaurus', imgUrl: '/img/styracosaurus.svg', type: 'land', power: 5, cost: 8, special: '', description: '' , doubled: false  },
      { _id: 35, name: 'syntarsus', imgUrl: '/img/syntarsus.svg', type: 'land', power: 7, cost: 15, special: '', description: '' , doubled: false  },
      { _id: 36, name: 'toucan', imgUrl: '/img/toucan.svg', type: 'air', power: 4, cost: 6, special: '', description: '' , doubled: false  },
      { _id: 37, name: 'triceratops', imgUrl: '/img/triceratops.svg', type: 'land', power: 8, cost: 20, special: '', description: '' , doubled: false  },
      { _id: 38, name: 'tyrannosaurus-rex', imgUrl: '/img/tyrannosaurus-rex.svg', type: 'land', power: 10, cost: 30, special: '', description: "'Don't move! He can't see us if we don't move!'" , doubled: false  },
      { _id: 39, name: 'velociraptor', imgUrl: '/img/velociraptor.svg', type: 'land', power: 8, cost: 20, special: '', description: "'That doesn't look very scary. More like a six-foot turkey.'" , doubled: false  },
      { _id: 40, name: 'whale', imgUrl: '/img/whale.svg', type: 'water', power: 10, cost: 30, special: '', description: '' , doubled: false  },
      { _id: 41, name: 'yinlong', imgUrl: '/img/yinlong.svg', type: 'land', power: 5, cost: 8, special: '', description: '' , doubled: false  },
      { _id: 42, name: 'panda', imgUrl: '/img/panda.svg', type: 'land', power: 4, cost: 6, special: '', description: "People will notice if we don't have a panda" , doubled: false  },
      { _id: 43, name: 'dracorex', imgUrl: '/img/dracorex.svg', type: 'land', power: 8, cost: 20, special: '', description: '' , doubled: false  },
      { _id: 44, name: 'beetle', imgUrl: '/img/beetle.svg', type: 'air', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 45, name: 'bee', imgUrl: '/img/bee.svg', type: 'air', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 46, name: 'penguin', imgUrl: '/img/penguin.svg', type: 'air', power: 5, cost: 8, special: '', description: "Dont\t you dare tell us that penguins can't fly" , doubled: false  },
      { _id: 47, name: 'crab', imgUrl: '/img/crab.svg', type: 'water', power: 7, cost: 15, special: '', description: '' , doubled: false  },
      { _id: 48, name: 'crocodile', imgUrl: '/img/crocodile.svg', type: 'water', power: 9, cost: 25, special: '', description: '' , doubled: false  },
      { _id: 49, name: 'dolphin', imgUrl: '/img/dolphin.svg', type: 'water', power: 6, cost: 10, special: '', description: '' , doubled: false  },
      { _id: 50, name: 'mothra', imgUrl: '/img/mothra.svg', type: 'air', power: 12, cost: 40, special: '', description: '"Mightiest Monster in all Creation. Ravishing a Universe for Love"' , doubled: false  }
    ]
  }


module.exports = { CARD_DATA:  CARD_DATA_OBJECT }
